### ISSUE TITLE
Spacy upgrade to 3.0+

### ISSUE THREAD

**Issue by gautierdag** [GEM-benchmark/NL-Augmenter#110]
Hi there,
Just wondering - is there any reason `spacy` is locked with the old version `spacy==2.2.4` in the main `requirements.txt`? 

Spacy 3.0 was quite a big upgrade from 2.2.4, and `3.1.0` was just released today so it might make sense to look forward and make that a requirement instead. 

I don't think any current implementations would break by this upgrade but I'm happy to make a PR for it and fix things if needed.

**Comment by kaustubhdhole** [comment]
Tagging @samsontmr here!

**Comment by aadesh11** [comment]
#117  Upgraded spacy to 3.0.0
