### ISSUE TITLE
issue while build

### ISSUE THREAD

**Issue by pawan2411** [GEM-benchmark/NL-Augmenter#122]
not sure why module is failing while building....i am using direct install for one library from git (see first line of requirements.txt)
it is working in local and also on multiple GCS vms (where i did dev).
reference: 
https://github.com/GEM-benchmark/NL-Augmenter/pull/113/checks?check_run_id=3040556102

**Comment by AbinayaM02** [comment]
Hi @pawan2411 : The build is failing because you're using invalid format for wptools installation in the requirements.txt file for your transformation. This is the original library: https://github.com/siznax/wptools. Use wptools==<version> instead of using your own fork of the library!

**Comment by pawan2411** [comment]
@AbinayaM02 because original wptools was using pycurl which is not supported in RHEL by default(i suppose RHEL is the one which is used to build), hence i changed wptools code, for this i also created a PR in wptools which was merged(https://github.com/siznax/wptools/pull/168), but I am not sure when will wptools officially update and release new version, so I have to give git link in requirements instead ( https://stackoverflow.com/questions/16584552/how-to-state-in-requirements-txt-a-direct-github-source ), also when i do "pip install -r requirements" this does work for me, not sure why this requirements file is not working in the build machine.

**Comment by pawan2411** [comment]
looks like updating setuptools will sort this out, did that in new commit...waiting for the next build @AbinayaM02

**Comment by AbinayaM02** [comment]
@pawan2411 : Setup.py has an argument called install_requires which doesn't accept the git links as is. That's the error thrown doing build. setuptools is already installed in the initial requirement in the github actions runner. So, not sure if the build will pass!
Let's wait and see.

**Comment by pawan2411** [comment]
@AbinayaM02 it failed again! let me check if we can do any workaround.

**Comment by pawan2411** [comment]
@AbinayaM02 added "wptools @ git+git://github.com/pawan2411/wptools@30738f1" line instead....
reference : https://stackoverflow.com/questions/26061610/pip-install-dependency-links
can u again start the build pls

**Comment by pawan2411** [comment]
@AbinayaM02 above fix worked! Closing the issue. Thanks
