### ISSUE TITLE
Add CUDA argument in evaluate.py to set the "is_cuda" flag in evaluate methods to False. (for non-Nvidia GPUs to use CPU)

### ISSUE THREAD

**Issue by timothy22000** [GEM-benchmark/NL-Augmenter#172]
Hi All,

I am using a Mac OS for my project so I am running into an issue when trying to evaluate my transformations. As I do not have Nvidia GPUs, I would like to use the CPU when working with PyTorch otherwise I would get an `"AssertionError: Torch not compiled with CUDA enabled".`

Mac OS users that do not have Nvidia GPU will have to set device = -1 to not use GPU:
MacOS: "AssertionError: Torch not compiled with CUDA enabled" 
https://github.com/allenai/allennlp/issues/877

This seems to be stemmed from the fact that there is currently no way to change the is_CUDA flag that is being set to TRUE by default in the `evaluate() `method inside `evaluate_text_classification.py` to FALSE. (There is code to set the device to 0 or -1 based on the `is_cuda` flag.)

I am able to run my evaluations by changing the `is_cuda` flag in the code. It will probably be better to make it an argument so that future users who want to use CPUs instead of GPUs to be able to do it when running `python evaluate.py -t [transformation] -task [task_type]`

I will be happy to make the required changes if that's something we'd want.

Thanks,
Tim

**Comment by AbinayaM02** [comment]
Hi @timothy22000 : Thanks for bringing this issue to notice. Instead of introducing an argument in the evaluate.py script, I would suggest adding the following code in evaluate_text_classification.py to automatically detect if GPU is present or not and set the is_cuda flag accordingly in the evaluate method,

```python
is_cuda=torch.cuda.is_available()
```
@kaustubhdhole : Let me know your thoughts.

**Comment by AbinayaM02** [comment]
Fix is merged. So, closing the issue.

**Comment by CANLAN-SC** [comment]
Well, I solve this problem by changing CUDA into cpu where the bug happens.
