### ISSUE TITLE
Language Detection

### ISSUE THREAD

**Issue by clauderouxster** [GEM-benchmark/NL-Augmenter#177]
How can we detect, which language is used for the evaluation on the fly?
We want to apply the correct transformation in "generate" on the fly according to the current language...

Thanks in advance

**Comment by AbinayaM02** [comment]
Hi @clauderouxster: I'm not sure if I understood your question correctly.
1. Are you asking about the current evaluation script not taking into account language as a parameter before evaluating a transformation? 
2. Do you want to detect language as part of your transformation?

**Comment by clauderouxster** [comment]
Hello,

I think the second point would be adequate. I would like to be able to detect, which language was associated to the sentence that is sent to generate. In the worse case, I guess I could use a language identifier, but if this information about the input language is already available, I would like to know how to access it.

regards,

**Comment by AbinayaM02** [comment]
Currently, each of the transformation has a variable called "languages" that is set manually to the respective languages the transformation will work on. Use can use the same approach for your transformation.

**Comment by clauderouxster** [comment]
Thank you...
