### ISSUE TITLE
Cannot Run `evaluate.py` Script

### ISSUE THREAD

**Issue by cascadianblue** [GEM-benchmark/NL-Augmenter#300]
I've tried running the `evaluate.py` script in [this Colab notebook](https://colab.research.google.com/drive/1Bj_0UrLm7OnV-DKEZwqcXHqWwga6kIF6?usp=sharing). I get the following error:

```
OSError: /usr/local/lib/python3.7/dist-packages/torchtext/_torchtext.so: undefined symbol: _ZNK3c104Type14isSubtypeOfExtESt10shared_ptrIS0_EPSo
```

**Comment by AbinayaM02** [comment]
Hi @cascadianblue: I have provided the solution in #126. Please try that and let me know if it worked.
