### ISSUE TITLE
Fix Breaking Line in Gender Neutral Rewrite Transformation

### ISSUE THREAD

**Issue by cascadianblue** [GEM-benchmark/NL-Augmenter#307]
[This line](https://github.com/GEM-benchmark/NL-Augmenter/blob/b84beccc6d7af31942cb690492cbcaafe4cef3aa/transformations/gender_neutral_rewrite/transformation.py#L27) is breaking the package.

`self.nlp = ...` should go under the `__init__()` method.

**Comment by cascadianblue** [comment]
@AbinayaM02 @kaustubhdhole it looks like someone named Tony Sun introduced this bug. I'm confused how this was approved, it looks like it is breaking everything

**Comment by tonysun9** [comment]
Thanks for pointing this out. Made a PR here: https://github.com/GEM-benchmark/NL-Augmenter/pull/324.
