### ISSUE TITLE
`GermanGenderSwap` missing `noun_pairs.json` file and incorrectly assumes the resources are on the script path

### ISSUE THREAD

**Issue by Saad-Mahamood** [GEM-benchmark/NL-Augmenter#313]
Hi @raft001,

It seems that in addition to issue #310 there are two other issues that need addressing:

* `noun_pairs.json` is missing. This needed on line 17.
* The script assumes that the resource *.json files will always be on the script path. Please instead do the following to resolve the path:
`file = os.path.join(os.path.dirname(os.path.abspath(__file__)), '<file_name>.json')`

Then `current_path` can be used as the absolute path to your resource files.

**Comment by raft001** [comment]
Hi @Saad-Mahamood, yes the file was missing, I've added it in a new PR. 
Thanks
