### ISSUE TITLE
`re.sub` method error during the evaluation

### ISSUE THREAD

**Issue by pithysr** [GEM-benchmark/NL-Augmenter#365]
Hi,
While running the `evaluate` method (for #246), I get an error in my `re.sub` method for one of the tests --most likely due to a problem with the escape characters. I can replace it with `string.replace` to solve the problem. However, this branch is already merged. Do you suggest creating a new branch or to leave the corresponding eval columns empty?

**Comment by AbinayaM02** [comment]
Hi @pithysr: Please feel free to open a new PR for the fix.
